[build]
command = "npm run build"
publish = "dist"
base = "/"

[dev]
command = "npm run dev"
targetPort = 5173
port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.stripe.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: blob: https: https://fonts.gstatic.com data:; connect-src 'self' https://api.stripe.com http://localhost:4242 https://models.inference.ai.azure.com https://*.stripe.com https://bmuvsbafvrvsgdplhvgp.supabase.co https://*.supabase.co wss://bmuvsbafvrvsgdplhvgp.supabase.co https://cdnjs.cloudflare.com; frame-src 'self' https://*.stripe.com; script-src-elem 'self' 'unsafe-inline' https://*.stripe.com https://cdnjs.cloudflare.com"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://bmuvsbafvrvsgdplhvgp.supabase.co/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/rest/*"
  to = "https://bmuvsbafvrvsgdplhvgp.supabase.co/rest/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://bmuvsbafvrvsgdplhvgp.supabase.co/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/realtime/*"
  to = "https://bmuvsbafvrvsgdplhvgp.supabase.co/realtime/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/storage/*"
  to = "https://bmuvsbafvrvsgdplhvgp.supabase.co/storage/:splat"
  status = 200
  force = true 